using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
public class ChangeAlphaAnRay : MonoBehaviour
{
   public CanvasGroup Sm;
   public CanvasGroup alttp;
   public CanvasGroup zebes;
   public CanvasGroup zelda;
   public CanvasGroup d1;
   public CanvasGroup d2;
   public CanvasGroup d3;
   public CanvasGroup d4;
   public CanvasGroup d5;
   public CanvasGroup d6;
   public CanvasGroup d7;
   public CanvasGroup d8;
   public CanvasGroup d9;
   public void SM()
   {
      Sm.alpha = 1;
      Sm.blocksRaycasts = true;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }

   public void Alttp()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 1;
      alttp.blocksRaycasts = true;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void Zebes()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 1;
      zebes.blocksRaycasts = true;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void Zelda()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 1;
      zelda.blocksRaycasts = true;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D1()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 1;
      d1.blocksRaycasts = true;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D2()
   {  
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 1;
      d2.blocksRaycasts = true;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D3()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 1;
      d3.blocksRaycasts = true;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D4()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 1;
      d4.blocksRaycasts = true;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D5()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 1;
      d5.blocksRaycasts = true;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D6()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 1;
      d6.blocksRaycasts = true;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D7()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 1;
      d7.blocksRaycasts = true;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D8()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 1;
      d8.blocksRaycasts = true;
      d9.alpha = 0;
      d9.blocksRaycasts = false;
   }
   public void D9()
   {
      Sm.alpha = 0;
      Sm.blocksRaycasts = false;
      alttp.alpha = 0;
      alttp.blocksRaycasts = false;
      zebes.alpha = 0;
      zebes.blocksRaycasts = false;
      zelda.alpha = 0;
      zelda.blocksRaycasts = false;
      d1.alpha = 0;
      d1.blocksRaycasts = false;
      d2.alpha = 0;
      d2.blocksRaycasts = false;
      d3.alpha = 0;
      d3.blocksRaycasts = false;
      d4.alpha = 0;
      d4.blocksRaycasts = false;
      d5.alpha = 0;
      d5.blocksRaycasts = false;
      d6.alpha = 0;
      d6.blocksRaycasts = false;
      d7.alpha = 0;
      d7.blocksRaycasts = false;
      d8.alpha = 0;
      d8.blocksRaycasts = false;
      d9.alpha = 1;
      d9.blocksRaycasts = true;
   }
}
